/*
 * This file is generated by jOOQ.
 */
package li.raphael.kokus.db.jooq.tables.records


import java.util.UUID

import li.raphael.kokus.db.jooq.tables.Recipe

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RecipeRecord() : UpdatableRecordImpl<RecipeRecord>(Recipe.RECIPE) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised RecipeRecord
     */
    constructor(id: UUID? = null, title: String? = null): this() {
        this.id = id
        this.title = title
        resetTouchedOnNotNull()
    }
}
