services:
    db:
        image: "postgres:18.4@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=localdev
            - POSTGRES_PASSWORD=*****
        command: >
            postgres
              -c shared_buffers=128MB
              -c fsync=off
              -c synchronous_commit=off
              -c full_page_writes=off
        # shared_buffers=128MB: Reduce memory usage for caching data pages
        # fsync=off: Disable disk flush to speed up writes
        # synchronous_commit=off: Avoid waiting for transaction durability confirmation
        # full_page_writes=off: Skip full-page WAL writes

        tmpfs:
            - /var/lib/postgresql:rw,noexec,nosuid,size=1g
