@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package li.raphael.kokus.db.jooq.keys


import li.raphael.kokus.db.jooq.tables.Recipe
import li.raphael.kokus.db.jooq.tables.records.RecipeRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val RECIPE_PKEY: UniqueKey<RecipeRecord> = Internal.createUniqueKey(Recipe.RECIPE, DSL.name("recipe_pkey"), arrayOf(Recipe.RECIPE.ID), true)
val RECIPE_TITLE_KEY: UniqueKey<RecipeRecord> = Internal.createUniqueKey(Recipe.RECIPE, DSL.name("recipe_title_key"), arrayOf(Recipe.RECIPE.TITLE), true)
