services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/base:ubuntu@sha256:edfb983aab9c579a385dc23c57d7d3703f5ec920124d99c16204a2cac465aab4
        volumes:
            - ..:/workspaces/kokus-recipe-app:cached
        command: sleep infinity
        depends_on:
            - db
