services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/base:ubuntu@sha256:91eff046d5c12318fc98e59258982b87ba896c467427ed8b5dab5a02107a5db7
        volumes:
            - ..:/workspaces/kokus-recipe-app:cached
        command: sleep infinity
        depends_on:
            - db
