/*
 * This file is generated by jOOQ.
 */
package li.raphael.kokus.db.jooq


import kotlin.collections.List

import li.raphael.kokus.db.jooq.tables.Recipe

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class DefaultSchema : SchemaImpl(DSL.name(""), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA: DefaultSchema = DefaultSchema()
    }

    /**
     * The table <code>recipe</code>.
     */
    val RECIPE: Recipe get() = Recipe.RECIPE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Recipe.RECIPE
    )
}
