/*
 * This file is generated by jOOQ.
 */
package li.raphael.kokus.db.jooq.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import li.raphael.kokus.db.jooq.DefaultSchema
import li.raphael.kokus.db.jooq.keys.RECIPE_PKEY
import li.raphael.kokus.db.jooq.keys.RECIPE_TITLE_KEY
import li.raphael.kokus.db.jooq.tables.records.RecipeRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Recipe(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RecipeRecord>?,
    parentPath: InverseForeignKey<out Record, RecipeRecord>?,
    aliased: Table<RecipeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RecipeRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>recipe</code>
         */
        val RECIPE: Recipe = Recipe()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RecipeRecord> = RecipeRecord::class.java

    /**
     * The column <code>recipe.id</code>.
     */
    val ID: TableField<RecipeRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>recipe.title</code>.
     */
    val TITLE: TableField<RecipeRecord, String?> = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<RecipeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RecipeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RecipeRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>recipe</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>recipe</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>recipe</code> table reference
     */
    constructor(): this(DSL.name("recipe"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<RecipeRecord> = RECIPE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<RecipeRecord>> = listOf(RECIPE_TITLE_KEY)
    override fun `as`(alias: String): Recipe = Recipe(DSL.name(alias), this)
    override fun `as`(alias: Name): Recipe = Recipe(alias, this)
    override fun `as`(alias: Table<*>): Recipe = Recipe(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Recipe = Recipe(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Recipe = Recipe(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Recipe = Recipe(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Recipe = Recipe(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Recipe = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Recipe = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Recipe = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Recipe = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Recipe = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Recipe = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Recipe = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Recipe = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Recipe = where(DSL.notExists(select))
}
