@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package li.raphael.kokus.db.jooq.tables.references


import li.raphael.kokus.db.jooq.tables.Recipe



/**
 * The table <code>recipe</code>.
 */
val RECIPE: Recipe = Recipe.RECIPE
